### ISSUE TITLE
TypeError: config.config is undefined

### ISSUE THREAD

**Issue by thijstriemstra** [SBoudrias/require.replace#7]
The plugin works good in development mode but after compilation with r.js it throws an error:

```
TypeError: s.config is undefined
http://site.static/js/site.min.js
Line 10
```

Where `s` is the `config` parameter:

```javascript
load: function (name, req, onLoad, config) {
			
			if( !config.config.replace ) {
				throw new Error('Require.replace need to be configured');
			}
```

My config contains the following (which is also used for the build):

```javascript
config: {
        replace: {
            videojsLocale: {
                pattern:  'LOCALE',
                value:    function() { return "nl"; },
                optimize: false
            },
            videojsRecordLocale: {
                pattern:  'LOCALE',
                value:    function() { return "nl"; },
                optimize: false
            }
        }
    },
    paths: {
        videojsLocale:              'lang/videojs/LOCALE',
        videojsRecordLocale:        'lang/videojs-record/LOCALE'
    }
```
```
Any ideas?

**Comment by SBoudrias** [comment]
I'll need to investigate, I haven't used this project recently (basically because I don't use require.js where I work anymore).

I just know it used to work on r.js/require.js ~2.1 (last time I used it must've been march 2014)

**Comment by thijstriemstra** [comment]
Forgot to mention I'm also using almond, maybe this strips out necessary info...

**Comment by SBoudrias** [comment]
This won't work if you rely on loading a script at run time (what you seem to be doing).

If you use almond, then concatenate everything into a single file as almond can't load other modules at run time.

**Comment by SBoudrias** [comment]
Hey, any news on this? Did my last comment help resolve your issue?

**Comment by thijstriemstra** [comment]
No I solved it by embedding json instead of loading externally. Closing.
